# Emplacement: fabric/config/configtx.yaml
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &Ministry
    Name: MinistryMSP
    ID: MinistryMSP
    MSPDir: ../organizations/peerOrganizations/ministry.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MinistryMSP.admin', 'MinistryMSP.peer', 'MinistryMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MinistryMSP.admin', 'MinistryMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MinistryMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MinistryMSP.peer')"

  - &Notary
    Name: NotaryMSP
    ID: NotaryMSP
    MSPDir: ../organizations/peerOrganizations/notary.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('NotaryMSP.admin', 'NotaryMSP.peer', 'NotaryMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('NotaryMSP.admin', 'NotaryMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('NotaryMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('NotaryMSP.peer')"

  - &Bank
    Name: BankMSP
    ID: BankMSP
    MSPDir: ../organizations/peerOrganizations/bank.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BankMSP.admin', 'BankMSP.peer', 'BankMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('BankMSP.admin', 'BankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('BankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('BankMSP.peer')"

  - &Municipality
    Name: MunicipalityMSP
    ID: MunicipalityMSP
    MSPDir: ../organizations/peerOrganizations/municipality.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MunicipalityMSP.admin', 'MunicipalityMSP.peer', 'MunicipalityMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MunicipalityMSP.admin', 'MunicipalityMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MunicipalityMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MunicipalityMSP.peer')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.example.com:7050
  EtcdRaft:
    Consenters:
    - Host: orderer.example.com
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Ministry
          - *Notary
          - *Bank
          - *Municipality

  DakarChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Ministry
        - *Notary
        - *Bank
        - *Municipality
      Capabilities:
        <<: *ApplicationCapabilities

  ThiesChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Ministry
        - *Notary
        - *Bank
        - *Municipality
      Capabilities:
        <<: *ApplicationCapabilities
