# Emplacement: fabric/config/crypto-config.yaml
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
    Users:
      Count: 1

PeerOrgs:
  - Name: Ministry
    Domain: ministry.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3

  - Name: Notary
    Domain: notary.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3

  - Name: Bank
    Domain: bank.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3

  - Name: Municipality
    Domain: municipality.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3
